Add support for the old bind database structure.
bloxlink/bloxlink-http pull request #24
Opened 2023-12-21 00:13 UTC by One-Nub

Automatically converts old bindings to the new format & saves them. When desired a flag can be flipped in the code to remove the old bindings from the database entirely.

2023-12-23 18:59 UTC, julien777z requested changes

2023-12-23 18:59 UTC, julien777z commented on src/resources/autocomplete.py
> +    yield interaction.build_response(choices[:25])
I'm not a fan of using the raw build_response method. Can you make a response.send_autocomplete method?

2023-12-23 18:59 UTC, julien777z commented on src/resources/autocomplete.py
> +    yield interaction.build_response(choices[:25])
You can make an API similar to the new Components which is nicer than referencing hikari.impl in the commands

2023-12-23 18:59 UTC, julien777z commented on src/resources/binds.py
> +    POP_OLD_BINDS: bool = False
Move this to the top of the file

2023-12-23 18:59 UTC, julien777z commented on src/resources/binds.py
> +    # Should be safe to presume this because the new format should not exist for people yet.
Don't use "presume" terminology because you shouldn't assume. You need to be certain or if not, use code to check for an edge case

2023-12-23 18:59 UTC, julien777z commented on src/resources/binds.py
> +        await bloxlink.mongo.bloxlink["guilds"].update_one(
We should never reference bloxlink.mongo. Add support for unsetting in the update_guild_data method

2023-12-23 18:59 UTC, julien777z commented on src/resources/binds.py
> +        await bloxlink.mongo.bloxlink["guilds"].update_one(
This is how I did it in the old code, so setting something to null unset it from the database https://github.com/bloxlink/bloxlink-official/blob/main/src/resources/modules/cache.py#L111

2023-12-23 18:59 UTC, julien777z commented on src/resources/binds.py
> +        await bloxlink.mongo.bloxlink["guilds"].update_one(
await update_guild_data(guild, test=None) to unset "test"

2023-12-23 18:59 UTC, julien777z commented on src/resources/binds.py
> +def convert_old_binds(items: dict, bind_type: ValidBindType) -> list:
Rename this to convert_v3_binds_to_v4

2023-12-23 18:59 UTC, julien777z commented on src/resources/binds.py
> +def convert_new_binds(items: list) -> dict:
Same with this one

2023-12-23 18:59 UTC, julien777z commented on src/resources/binds.py
> +                # Display name is/was not converted, so it is lost.
Set it to None

2023-12-23 18:59 UTC, julien777z commented on src/resources/binds.py
> +                    # Group name is/was not converted, so it is lost.
Same here - the field should always exist

2023-12-23 18:59 UTC, julien777z commented on src/resources/binds.py
> +                    # Group name is/was not converted, so it is lost.
You can also fetch the name with an http request

2023-12-23 18:59 UTC, julien777z commented on src/resources/binds.py
> +                continue
Add a newline before continue to make it consistent with how I usually code

2023-12-23 19:07 UTC, julien777z submitted a review, later dismissed

2023-12-23 19:07 UTC, julien777z commented on src/resources/binds.py
> +                # Add removeRoles to role_binds entry because (for what I see) it shows up there too?
This shouldn't be a question - if it's there then it's there

2023-12-24 02:06 UTC, One-Nub commented on src/resources/binds.py
> +    # Should be safe to presume this because the new format should not exist for people yet.
In that case, I think it would be best to make a database field that stores the state of the binds being converted vs not.

We *can* convert every time and store again, but if someone removed a bind it could cause a mismatch, causing the bind to be made again (to assume an alternative logic would be "check the existing binds and for any of the other format, if a bind is in the old format but not the new one, store that").

If there aren't any objections to that, I'll add a "converted_binds" field that will be set to true when the conversion is done the first time, and that will be used to determine if we need to convert or not. Once the old bindings are removed that field will be removed with it.

2023-12-24 02:51 UTC, One-Nub commented on src/resources/binds.py
> +                # Add removeRoles to role_binds entry because (for what I see) it shows up there too?
I was questioning it because I was repeating what I saw based on bind data that the prior bot made, I didn't fully validate that entry though.
Looking into it more now, it's not what I assumed it is. It's the list of roles the user chose to remove for the *latest* select-rank style binding that they made. (Irrespective of the entire group bind, if any)
https://github.com/bloxlink/bloxlink-official/blob/d25a45bc115a4fa581ddffaabb35b154f66fdfdf/src/commands/bind.py#L230

I am going to guess this was done in error in the prior codebase since the logic for applying binds there does not appear to refer to that field. If there are no objections, I propose removing that logic from the conversion method entirely instead.

2023-12-26 00:06 UTC, julien777z commented on src/resources/binds.py
> +    # Should be safe to presume this because the new format should not exist for people yet.
sounds good

2023-12-28 22:34 UTC, merged