Implementing the /viewbinds command
bloxlink/bloxlink-http pull request #9
Opened 2023-05-03 23:13 UTC by One-Nub

Necessary things to complete before merge:
- [X] Autocomplete for arguments
- [X] Pagination for the viewbind prompt
- [ ] Redesigning/improving the viewbind embed

---

This pull request contains the code implementing the viewbind command. This consists of adding autocomplete handling to the codebase, and adding structures that represent a binding.

2023-05-04 03:33 UTC, julien777z requested changes

2023-05-04 03:33 UTC, julien777z commented on src/commands/viewbinds.py
> +    custom_id_data = interaction.custom_id.split(":")
I wrote a handler for this here https://github.com/bloxlink/bloxlink-http/blob/master/src/resources/component_helper.py#L64

2023-05-04 03:33 UTC, julien777z commented on src/commands/viewbinds.py
> +    custom_id_data = interaction.custom_id.split(":")
index here starts at 1 btw

2023-05-04 03:33 UTC, julien777z commented on src/commands/viewbinds.py
> +    custom_id_data = interaction.custom_id.split(":")
I'd prob just edit the handler so it can return multiple values with one function call.

2023-05-04 03:33 UTC, julien777z commented on src/commands/viewbinds.py
> +    # 15 minute timeout on prompts. Woo stateless.
wym timeout, each button press gives u a new 15 mins assuming you defer it

2023-05-04 03:33 UTC, julien777z commented on src/commands/viewbinds.py
> +    bot_user = await bloxlink.rest.fetch_my_user()
this http call isn't necessary

2023-05-04 03:33 UTC, julien777z commented on src/commands/viewbinds.py
> +        "Please use `/bind` to make a new role bind, or try again with different options."
indent the second line

2023-05-04 03:33 UTC, julien777z commented on src/commands/viewbinds.py
> +    if page_components is str:
I don't understand what you're trying to do here

2023-05-04 03:33 UTC, julien777z commented on src/commands/viewbinds.py
> +    if page_components is str:
str is a built-in function and will only return true if page_components is str, which it is not

2023-05-04 03:33 UTC, julien777z commented on src/commands/viewbinds.py
> +                embed.add_field(f"{(await get_group(group)).name} ({group})", "\n".join(rank_map[group]))
this will raise an exception if the group is not found (such as an invalid id, or if the group was deleted by roblox)

2023-05-04 03:33 UTC, julien777z commented on src/commands/viewbinds.py
> +async def build_page_components(
this can prob be abstracted into a common utility for other paginating needs

2023-05-04 03:33 UTC, julien777z commented on src/commands/viewbinds.py
> +    if id_filter and str(id_filter).lower() != "none":
why are you casting to a str and checking? Can you just do `if id_filter`

2023-05-04 03:33 UTC, julien777z commented on src/resources/binds.py
> +        if self.removeRoles:
we don't use camelCase in python

2023-05-04 03:33 UTC, julien777z commented on src/resources/binds.py
> +    async def get_bind_string(self, guild_id: int, include_id=True, group_data=None) -> str:
can you just override `__str__` for this?

2023-05-04 03:33 UTC, julien777z commented on src/resources/binds.py
> +class GuildBind(BaseGuildBind):
if we're gonna use GuildBind then it should be used throughout the bot

2023-05-04 03:33 UTC, julien777z commented on src/resources/binds.py
> +async def role_ids_to_names(guild_id: int, roles: list) -> str:
why is this in binds.py

2023-05-04 03:33 UTC, julien777z commented on src/resources/binds.py
> +async def role_ids_to_names(guild_id: int, roles: list) -> str:
I'd probably define this in bloxlink.py

2023-05-04 03:33 UTC, julien777z commented on src/resources/binds.py
> +        return ""
this will already return "" if you call `", ".join(output_list)` with an empty list

2023-05-04 03:33 UTC, julien777z commented on src/resources/commands.py
> +    for command in slash_commands.values():
sir

2023-05-04 03:33 UTC, julien777z commented on src/resources/commands.py
> +    for command in slash_commands.values():
this function is O(n^3)

2023-05-04 03:39 UTC, JohnV50 commented on src/resources/commands.py
> +    for command in slash_commands.values():
agreed

2023-05-04 03:44 UTC, One-Nub commented on src/resources/commands.py
> +    for command in slash_commands.values():
I primarily based it on the way handle_component does it, can look into improving big o efficiency of it

2023-05-04 03:46 UTC, One-Nub commented on src/resources/binds.py
> +    async def get_bind_string(self, guild_id: int, include_id=True, group_data=None) -> str:
don't believe __str__ can be async? could be wrong, I can look into it

2023-05-04 03:47 UTC, One-Nub commented on src/commands/viewbinds.py
> +    if id_filter and str(id_filter).lower() != "none":
for the custom_id, I include id_filter regardless of it is set or not, so it comes through as `None` as a string literal

Could change the custom_id generator to just not add that element to the custom_id if id_filter is none when making the buttons

2023-05-04 03:49 UTC, One-Nub commented on src/commands/viewbinds.py
> +    if page_components is str:
typically, it is not a str, no
line 227, I return a string if the category is invalid - in which case the bot would reply with that message.

2023-05-04 03:49 UTC, One-Nub commented on src/commands/viewbinds.py
> +    bot_user = await bloxlink.rest.fetch_my_user()
guess I'll have to look into another way to get the bot user then, since from my scouring of the hikari docs I couldn't find a way to get the avatar of the bot account without making a rest request.

2023-05-04 03:50 UTC, One-Nub commented on src/commands/viewbinds.py
> +    # 15 minute timeout on prompts. Woo stateless.
with the stateless nature of the handling, I figured it would be logical that after 15 mintues a prompt could be considered "stale" and the user should just make another rather than having the bot continue to edit that message.

could be changed to just not do anything though, up to you

2023-05-04 03:53 UTC, One-Nub commented on src/commands/viewbinds.py
> +    return interaction.build_response(choices[:25])
The first option is a `view all binds` prompt that shows up regardless of the other options listed (except when matching user input). If a user has over 25 I would infer that they either know the IDs or will just choose view all binds

2023-05-04 03:57 UTC, One-Nub commented on src/commands/viewbinds.py
> +        if bind_type == "asset" and not asset and "asset".startswith(user_input):
it's this way so that way the prompt can show relevant options when a user puts in a single or a few characters (like `a` or `bad`) rather than having the bot show nothing to autocomplete

the set would get rid of the bools, guess I'd still have to iterate over the set to add the choices but it would result in cleaner code, will fix

2023-05-04 04:10 UTC, One-Nub commented on src/commands/viewbinds.py
> +            user_input = option.value
in our case this shouldn't matter too much since by this point (with the fun O(N^3) code) that option should at least exist (since the interaction isn't dispatched to the method except when it matches our choice name)

but I can look into making it a one-liner

2023-05-04 04:12 UTC, One-Nub commented on src/resources/binds.py
> +        if self.removeRoles:
removeRoles is how it is setup in the database to my knowledge (looking at quickbinds), I can look into changing the variable to snake_case & see if the dataclass will handle it accordingly or if I'll have to do some conversion

2023-05-04 04:19 UTC, One-Nub commented on src/commands/viewbinds.py
> +        filtered_binds = filter(lambda b: str(b).startswith(user_input), id_list)
as far as `==` vs `startswith()` goes, it's handling it that way so that way if a user inputs a "3" it'll show the IDs that start with a 3 (ex `35876262` will show)

iteration count can probably be reduced by using sets instead, will look into it

2023-05-04 04:21 UTC, One-Nub commented on src/commands/viewbinds.py
> +        if option.name == "category":
there's only two options at most in this case though? feels unnecessary to me unless we're really striving for that extra loop cycle to not happen, but with the concept of good practice, I'll add it

2023-05-04 04:29 UTC, One-Nub commented on src/resources/commands.py
> +    for command in slash_commands.values():
to elaborate, as I mentioned in a comment earlier-on, its doing all the iterations so that way it's pretty much guaranteed to only dispatch to the right method - I'll still look into improving the efficiency tho 

just from thinking about it, `autocomplete_handlers` is a map, so I should just be able to take the focused option name and call it which would bring big o down to O(N^2) I believe
past that would require more thinking, don't think I can really get lower without just forcing one autocomplete method to handle both/all options which is messy imo

2023-05-04 05:19 UTC, One-Nub commented on src/commands/viewbinds.py
> +        if option.name == "category":
looking at the code more, there's no need to break out of the loop here? both options are needed for the rest of the code, and again with only two variables it's not that big of a deal 

its if/elif, I could make then both just `if` and continue at the end of their respective if block rather than `if/elif` but they'll effectively work the same
```python
for option in interaction.options:
    if option.name == "category":
        ...
        continue
    
    if option.name == "id":
        ...
        continue
```

Default case, if there's no id then id_option is never set, so it just stays as none

2023-05-09 20:17 UTC, julien777z requested changes
~~this is not good, probably revert that, the part where it needs to find a match for the autocomplete handler~~ done

2023-05-14 03:30 UTC, One-Nub commented on src/commands/viewbinds.py
> +            label="\u2B9C",
The unicode text I chose for both buttons doesn't show on android. Should change, might reuse the button emojis from the current /help prompt on the main bot, not sure yet.

2023-05-15 07:15 UTC, DARKVEYDERK01 commented
Muy bien

2023-05-16 22:46 UTC, One-Nub commented on src/commands/viewbinds.py
> +    bot_user = await bloxlink.rest.fetch_my_user()
As of right now doesn't look like this can be done; I've asked about it in the hikari support server to see if there is some way.

An alternative is to either not include the image in the prompt, or just hardcode the favicon image that the site uses (since that's the only publicly available place I think the bot icon is hosted which would stay constant).

2023-05-17 15:33 UTC, One-Nub commented on src/commands/viewbinds.py
> +    await set_components(message, components=[components])
looks like this is the "emoji bug" that other devs have talked about, where interaction edits use the 'old' permission system while message edits (which is what set_components) use the 'new' one

tldr of differences:
- old: can use any emoji on platform as along as `@everyone` has use external emojis perm
- new: bot needs to share server with emoji, bot needs perms to use external emojis

not a major issue in my case - just results in some nuances with how i'm styling the embed - might need to shy away from emoji use or just ignore the visual annoyances since my local bot won't be in the server(s) where emojis are stored

2023-05-23 01:39 UTC, merged